from __future__ import annotations

from enum import StrEnum


class Error(StrEnum):
    """Centralized user-facing error message templates."""

    LoginNonce = "Camera did not return a login nonce"
    UdpRelayRequiresUid = "UDP relay requires a camera UID"
    CameraAddressRequired = "Camera needs address, cached_address, or a UID reachable by discovery"
    CameraNotConnected = "Camera is not connected"
    BatteryRequestFailed = "Battery request failed"
    ShortBaichuanHeader = "Short Baichuan header"
    CameraClosedConnection = "Camera closed the connection"
    AesWithoutKey = "AES cipher selected without a key"
    InstallDependencies = "Install dependencies with: python -m pip install -r requirements.txt"
    UdpBaichuanTimeout = "Timed out waiting for UDP Baichuan data"
    LocalUdpP2pNoReply = "No accepted local UDP P2P reply from camera"
    P2pLookupNoServers = "Reolink P2P lookup did not return register/relay servers"
    RegisterNoConnectionDetails = "Reolink register did not return connection details"
    MissingCameraConnectionId = "Connection did not return a camera connection id"
    P2pLookupNoReply = "No Reolink P2P lookup reply with register/relay servers"
    RegisteredConnectionNoReply = "No accepted C2D_T/D2C_CFM reply from registered connection candidates"
    HlsRequiresH264OrH265 = "HLS requires H264 or H265 camera video"
    InvalidQuality = 'quality must be "high" or "low"'
    NoReadableVideoFrames = "BCMedia stream did not contain readable video frames"
    SelectOneCamera = "Specify --camera when the config has zero or multiple cameras"
    SdReplayNeedsNameAndStart = "Replay download needs file name and startTime"
    SdRemoveNeedsConfirm = "Refusing to remove an SD-card file without confirm=True"
    SdRemoveNotImplemented = "SD-card file removal is not wired yet; list/download are the current safe operations"
    SdFormatNeedsConfirm = 'Refusing to format the SD card without confirm=True and confirmation_text="FORMAT SD CARD"'
    SortValue = 'sort must be "asc", "desc", or None'
    StreamTypeOrQuality = "Use either stream_type or quality, not both"
    BatteryMode = 'mode must be "reconnect" or "online"'
    StreamValue = 'stream must be "mainStream", "subStream", "externStream", "high", or "low"'
    StreamRoute = "Use /{camera}/{quality} or /{camera}/{quality}/hls.m3u8"
    HlsRoute = "Use /{camera}/{quality}/hls.m3u8"
    HlsSegmentRoute = "Use /{camera}/{quality}/segments/{sequence}.ts"
    InvalidHlsSegmentSequence = "Invalid HLS segment sequence"
    HlsSegmentExpired = "HLS segment is no longer available"
    SdDownloadTimeout = "Timed out waiting for download response"
    RecordStopTimeout = "Timed out waiting for recording to stop"
    EventListenerClosed = "Camera event listener is closed"
    EventStartFailed = "Event listener start failed with response {response_code}"
    VoiceNotSupported = "Camera does not report usable talk/voice ability"
    VoiceNeedsAdpcm = "Camera talk protocol requires ADPCM audio"
    VoiceFfmpegRequired = "ffmpeg is required to play audio files through camera voice"
    VoiceFfmpegFailed = "ffmpeg failed while preparing voice audio: {detail}"
    VoiceFfprobeFailed = "ffprobe failed while checking voice audio: {detail}"
    VoiceFileNotFound = "Voice audio file does not exist: {path}"
    VoiceNoAudioStream = "Voice audio file has no audio stream: {path}"
    VoiceMicrophoneDependency = "Install sounddevice to use microphone voice input"
    VoiceNoInput = "Use file=..., microphone=True, tone=..., or siren=True for voice playback"
    PirStateMissing = "Camera did not return PIR rfAlarmCfg"
    LedStateMissing = "Camera did not return LedState"
    IrModeValue = 'IR mode must be "on", "off", or "auto"'

    LoginFailed = "Login failed with response {response_code}"
    TimedOutResponse = "Timed out waiting for response to message {msg_id} #{msg_num}"
    StreamStartFailed = "Stream start failed with response {response_code}"
    StreamStartTimeout = "Timed out waiting for stream start response #{msg_num}"
    BatteryInfoFailed = "Battery info failed with response {response_code}"
    PirInfoFailed = "PIR info failed with response {response_code}"
    PirSetFailed = "PIR set failed with response {response_code}"
    IrInfoFailed = "IR light info failed with response {response_code}"
    IrSetFailed = "IR light set failed with response {response_code}"
    SnapshotInfoFailed = "Snapshot info failed with response {response_code}"
    SnapshotDataFailed = "Snapshot data failed with response {response_code}"
    SnapshotSizeMismatch = "Snapshot received {actual_size} bytes, expected {expected_size} bytes"
    NoCameraNamed = "No camera named {name!r}"
    NoCameraNamedWithAvailable = "No camera named {name!r}. Available cameras: {available}"
    InvalidBaichuanMagic = "Invalid Baichuan magic 0x{magic:08x}"
    NoAcceptedDiscoveryReply = "No accepted discovery reply from {dest}"
    FfmpegNoOutput = "ffmpeg created no output from {frames} {codec} frames"
    SdBestAttemptMismatch = "Best attempt {label} downloaded {written} bytes, expected {expected_size} bytes. Tried: {attempts}"
    SdDownloadFailed = "SD download failed. Tried: {attempts}"
    SdPreviewFailed = "SD preview failed. Tried: {attempts}"
    Response = "response {response_code}"
    ReplaySeekFailed = "ReplaySeek failed with response {response_code}"
    ReplayFileDetailFailed = "Replay file detail failed with response {response_code}"
    SdFormatFailed = "SD-card format failed with response {response_code}"
    SdDiskInfoFailed = "SD-card disk info failed with response {response_code}"
    SdDayRecordsFailed = "SD-card day records failed. Tried: {attempts}"
    DownloadSizeMismatch = "Downloaded {actual_size} bytes, expected {expected_size} bytes"
    Mp4ConversionFailed = "Downloaded BCMedia, but MP4 conversion failed; raw stream saved to {raw_path}: {exc}"
    UnknownCommand = "Unknown command: {command}"
    SdPreviewDumpTooLarge = "SD preview dump exceeded the {max_bytes} byte safety limit; pass max_bytes to adjust it"
    ReceiveTimeout = "Timed out waiting for camera data"
    LoginConnectionClosed = (
        "Camera closed the connection during login negotiation; "
        "modern firmware only accepts max_encryption='aes'"
    )
    ConfigParseFailed = "Could not parse config {path} as JSON ({json_error}) or as TOML ({toml_error})"
    CameraConfigMissingName = "Camera config entry {index} is missing the required \"name\" field"
    StreamKeyframeTimeout = "Timed out waiting for a keyframe from the camera stream"
    IrSetTimeout = "Timed out waiting for IR light set response #{msg_num}"
    PirSetTimeout = "Timed out waiting for PIR set response #{msg_num}"


class Log(StrEnum):
    """Centralized CLI/debug log message templates."""

    Stopped = "stopped"
    NoUidAddresses = "No camera addresses found for this UID."

    LocalUdpP2pFailed = "[pyneolink] Local UDP P2P failed: {exc_type}: {exc}"
    IgnoringUnmatchedMessage = (
        "[pyneolink] Ignoring unmatched message msg_id={msg_id} "
        "msg_num={msg_num}; waiting for msg_num={expected_msg_num}"
    )
    StreamStopReturned = "[pyneolink] Stream stop returned {response_code}; ignoring"
    StreamStopCloseFailed = "[pyneolink] Stream stop failed during close: {exc_type}: {exc}"
    StreamKeepaliveReplyFailed = "[pyneolink] Failed to reply to stream keepalive: {exc_type}: {exc}"
    ConfigWritten = "wrote {path}"
    DiscoveryHit = "{host}:{port}{uid} source={source}"
    CameraConnected = "{name}: connected"
    RebootSent = "{name}: reboot command sent"
    VideoPacketsWritten = "wrote {count} video packets to {output}"
    SnapshotSaved = "saved snapshot to {output}"
    RecordingStarted = "recording to {output}; press Ctrl+C to stop"
    RecordingSaved = "saved recording to {output}"
    EventReceived = "{time}: {event}"
    VoiceReady = "voice connected; speak now"
    VoicePlaying = "voice connected; playing {input}"
    VoiceSent = "voice sent"
    SirenSent = "siren command sent"
    Error = "Error: {exc}"
    Serving = "Serving camera streams on http://{host}:{port}/"
    OpenLocal = "Open locally with http://{host}:{port}/"
    Url = "  {url}"
    Pyneolink = "[pyneolink] {message}"
    PreviewCacheWorkerStillRunning = "Preview cache worker is still running; keeping cache file {path}"
    InfoFlagIgnored = "[pyneolink] Ignoring --info because the {command!r} command was given"
